version: '3.8'

services:
  frontend:
    build:
      context: ./client 
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./server  
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"

